name: Clippy

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

jobs:
  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust_version: ["1.64.0"]

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Rust toolchain
      run: |
        rustup default ${{ matrix.rust_version }}
        rustup component add clippy

    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
